config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  # Статические страницы
  get "/help",      to: "static_pages#help"
  get "/about",     to: "static_pages#about"
  get "/contact",   to: "static_pages#contact"

  # Аутентификация и авторизация
  get  "/signup",   to: "users#new"
  get  "/login",    to: "sessions#new"
  post "/login",    to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: "logout"

  # Управление пользователями
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [ :edit ]
  resources :password_resets,     only: %i[new create edit update]
  resources :microposts,          only: %i[create destroy]
  resources :relationships,       only: %i[create destroy]

  # Дополнительные служебные маршруты
  get "up"              => "rails/health#show",         as: :rails_health_check
  get "service-worker"  => "rails/pwa#service_worker",  as: :pwa_service_worker
  get "manifest"        => "rails/pwa#manifest",        as: :pwa_manifest
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
</small>
<nav>
<ul>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Contact", contact_path %></li>
<li><a href="https://news.railstutorial.org/">News</a></li>
</ul>
</nav>
</footer>

app/views/layouts/_head.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Внешние библиотеки через CDN (если нужны, но учитывайте, что они грузятся как обычные скрипты) -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" crossorigin="anonymous"></script>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
<!-- Удаляем javascript_include_tag 'application', чтобы не было конфликта с importmap -->

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
         <li><%= link_to "Users", users_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= button_to "Log out", logout_path, method: :delete, form: { data: { turbo: "true" } }, class: "btn btn-danger" %></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <%= render 'layouts/head' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <%= render 'layouts/header' %>
    </header>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>